- docs/HISTORY.txt
- ftw/solr/patches/utils.py
- ftw/solr/tests/test_utils.py
Fixes issue where a dot in a search term causes the `search_pattern` template to be circumvented, and therefore messing up the relevancy ranking because none of the weighting of `Title` or `Description` is applied, no wildcards are added, etc.
@buchi
> Allow dots in simple terms / simple searches.

- docs/HISTORY.txt
- ftw/solr/browser/results.pt
- ftw/solr/browser/search.py
@maethu this makes it possible to render the results correctly, when the Catalog returns the result and Solr isn't involved. E.g. when searching for Keywords/Subjects.
> Make it possible to render Searchview when getting brains.

- docs/HISTORY.txt
- ftw/solr/browser/resources/ftwtheming.scss
- ftw/solr/browser/resources/livesearch.js
- ftw/solr/browser/resources/solr.css
- ftw/solr/viewlets/templates/searchbox.pt
According to access4all the `only in current folder section` item has to be selectable with the keyboard.
> Accessibility: Make `only in current folder section` selectable in the dropdown menu.

- docs/HISTORY.txt
- ftw/solr/browser/available-facets.pt
- ftw/solr/browser/resources/facets.js
- ftw/solr/browser/resources/ftwtheming.scss
- ftw/solr/browser/resources/solr.css
- ftw/solr/browser/results.pt
- ftw/solr/browser/search.js
- ftw/solr/browser/selected-facets.pt
- ftw/solr/profiles/default/jsregistry.xml
- ftw/solr/upgrades/20160217163924_register_javascript_for_accessiblity_handling_of_the_facets/jsregistry.xml
- ftw/solr/upgrades/20160217163924_register_javascript_for_accessiblity_handling_of_the_facets/upgrade.py
According to access4all the facets of the solr search has to be
reachable with the keyboard.
Go trough the filter by hitting tab. This will focus the filter.
Controls on the filter:
- right arrow: open the focused filter
- down arrow: open the focused filter
- enter: open the focused filter
Controls on open filter:
- escape: close the open filter 
- left arrow: close the open filter
- down arrow: focus next facet
- up arrow: focus previous facet
> Implement accessibility support for solr facets.

- docs/HISTORY.txt
- ftw/solr/browser/configure.zcml
- ftw/solr/browser/facets.py
The current implementation does not respect the facets configured in the Solr control panel. Some default facets are rendered instead (portal_type,  site_section, modified).
This commit removes the hard coded facets so that the configured facets are rendered.
I also noticed that the facet "modified" is rendered even if it is not configured. This will be handled in an upcoming issue.
/cc @elioschmutz, @maethu
> Respect the facets configured in the Solr control panel.

- docs/HISTORY.txt
The release notes of 1.5.0 got messed up during the release process: the changes introduced in the commit 3507cce4fd7ff1 (via https://github.com/4teamwork/ftw.solr/pull/60) did not go into this release, they are still only available on the master branch:
> Fix readme.

- docs/HISTORY.txt
- ftw/solr/browser/available-facets.pt
Fixes https://github.com/4teamwork/ftw.solr/issues/59
Plone wraps `https` links with a span tag by default. This behavior
breaks the dropdown functionality on the solr searchpage.
As documented in https://github.com/plone/Products.CMFPlone/blob/4.3.7/Products/CMFPlone/skins/plone_ecmascript/mark_special_links.js#L5
add the `link-plain` class to prevent this behavior.
> Disable marking special links on dropdown links in searchpage.

- docs/HISTORY.txt
- ftw/solr/behaviors.py
- ftw/solr/configure.zcml
- ftw/solr/testing.py
- ftw/solr/tests/__init__.py
- ftw/solr/tests/test_behaviors.py
- setup.py
Adds two new behaviors:
- ftw.solr.behaviors.IShowInSearch
- ftw.solr.behaviors.ISearchwords
These behaviors provide the two fields "show in search" an "searchwords" as they are already existing as schema-extender for Archetypes.
> Dexterity behaviors for search fields

- docs/HISTORY.txt
- ftw/solr/upgrades/20150921133623_remove_custom_utilities/componentregistry.xml
This fixes an existing upgrade step which incorrectly added the Solr index queue processor utility in 1.5.0.
> Fix faulty upgrade step.

- docs/HISTORY.txt
- ftw/solr/browser/resources/searchpage.scss
- sources.cfg
- test-plone-4.3.x.cfg
> Style selected facetes.

- docs/HISTORY.txt
- ftw/solr/browser/resources/livesearch.js
- ftw/solr/viewlets/templates/searchbox.pt
Closes parts of https://github.com/4teamwork/bern.web/issues/1152
Result text should only be visible to screenreaders if necessary.
> Prevent the result text from read out through the screenreader.

- docs/HISTORY.txt
- ftw/solr/browser/resources/livesearch.js
Abort livesearch init if no searchfield is available to make the script failsafe.
> Abort livesearch init if no searchfield is available

- docs/HISTORY.txt
- ftw/solr/patches/utils.py
- ftw/solr/tests/test_utils.py
This is a backport of 8650602b45bac2674851e921b3dc5e55f6147f5f from 1.7.x line
Fixes issue where a comma/hyphon in a search term causes search_pattern template to be circumvented.
Also check PR https://github.com/4teamwork/ftw.solr/pull/45
Same issue with dots.
> Allow hyphons and commas simple terms and simple searches.

- docs/HISTORY.txt
- ftw/solr/browser/search.py
When an exception is raised while querying, the solr_response attribute was not set but later accessed by the template.
By setting it by default to an empty list we make sure that we do not produce unecessary AttributeErrors.
> Avoid AttributeError "solr_response" on solr errors. [1.7.x]

- docs/HISTORY.txt
- ftw/solr/browser/search.py
When an exception is raised while querying, the solr_response attribute was not set but later accessed by the template.
By setting it by default to an empty list we make sure that we do not produce unecessary AttributeErrors.
> Avoid AttributeError "solr_response" on solr errors.

- docs/HISTORY.txt
- ftw/solr/browser/available-facets.pt
- ftw/solr/browser/search.js
- ftw/solr/browser/selected-facets.pt
Do not use TALES string expressions for facet links, since it automatically transforms chars into html entities.
This fixes several JS problems + re-enabled the search highlight feature of the search function.
I also call now the "scanforlinks" (mark_special_link.js) method to mark the external links (external resources).
> Fix html entities in querystring. This produced strange js errors.

- docs/HISTORY.txt
- ftw/solr/browser/facets.py
This prevents projects having customizations of selected facets from crashing when displaying the search results.
> Make getting the facets more robust.

- docs/HISTORY.txt
- ftw/solr/browser/resources/livesearch.scss
Closes https://github.com/4teamwork/ftw.solr/issues/85
The font has been set through the standard jqueryUI styling.
But we want the predefined font settings from ftw.theming.
> Fix font for livesearch results

- docs/HISTORY.txt
- ftw/solr/behaviors.py
- ftw/solr/tests/test_behaviors.py
- ftw/solr/tests/test_indexers.py
- ftw/solr/upgrades/20170403110134_update_searchwords_index/upgrade.py
This applies only for DX content.
> Lower searchwords in ISearchwords indexer, since the value is always lowered in ftw.solr.

- docs/HISTORY.txt
- ftw/solr/profiles/default/viewlets.xml
The current `viewlets.xml` only orders and hides the viewlets for the "Sunburst Theme"-skin. If you use another skin and you install `ftw.solr` you wont get the desired viewlet-changes.
> Hide and order the viewlets for all skins and not only for the "Sunburst Theme"-skin

- ftw/solr/indexers.py
- ftw/solr/upgrades/20170531122255_reindex_snippet_text/upgrade.py
This fixes the Problem where the < sign is not escaped and leads to the footer being displayed twice.
The upgrade step is very general since it could be a issue on a lot of types. But i'm not sure if its a good idea to put it as general since it could be quite expensive to run.
> escape less than and greater than sign

- docs/HISTORY.txt
- ftw/solr/browser/livesearch.py
- ftw/solr/browser/resources/livesearch.js
- ftw/solr/locales/de/LC_MESSAGES/ftw.solr.po
- ftw/solr/locales/en/LC_MESSAGES/ftw.solr.po
- ftw/solr/locales/fr/LC_MESSAGES/ftw.solr.po
- ftw/solr/locales/ftw.solr.pot
- ftw/solr/locales/it/LC_MESSAGES/ftw.solr.po
This also needs some solr configuration:
The livesearch handler needs to be extended with the spellcheck component: 
Example: https://github.com/4teamwork/winterthur.web/pull/782/files#diff-5ff03d16bffdd554565a07f7e1b37899R80
> Implement first suggestion on livesearch

- ftw/solr/viewlets/templates/searchbox.pt
Previously the submit was like a hidden tabindex after the search box. The user can still submit from the search input.
> Remove search viewlet submit from tabindex.

- docs/HISTORY.txt
- ftw/solr/contentlisting.py
- ftw/solr/tests/test_searchview.py
If we use the live search and the result has a `GET` parameter in his URL then `ftw.solr` generates an invalid URL with two `?`. Example `http://nohost/plone/object?this=that?searchterm=test`
This PR handles this edge-case.
Extranet Ticket: https://extranet.4teamwork.ch/support/stadt-winterthur/tracker-web/27
> Prevent invalid url if the object has a get parameter in his path.

- docs/HISTORY.txt
- ftw/solr/browser/resources/searchpage.scss
The selector must be more explicit, otherwise the `list()` mixin wins.
> Fix position of facet closing icon.

- docs/HISTORY.txt
- ftw/solr/browser/search.js
This means we can use a copy of the search view with a different endpoint and we can still use the same js.
> Use searchform action as endpoint in search.js.

- docs/HISTORY.txt
- ftw/solr/patches/mangler.py
portal_catalog query: `{'Subject': {'query':['Tag 1', 'Tag 2], 'operator': 'and'}`
Now results in `+Subject:("Tag 1" AND "Tag 2")`
Before the result was `+Subject:(Tag 1 AND Tag 2)`
This way solr search for `Tag AND 1 AND Tag AND 2`
> Always quote values of a list query containing an operator.

- docs/HISTORY.txt
- ftw/solr/browser/search.py
- ftw/solr/tests/test_searchview.py
Problem:
Solr returns `<em>`-highlighted text, but the text is not html escaped.
Using "<" for example can cause the page templating engine to drop
closing tags.
Solution:
Escape all text in the snippet endpoint, except for the highlighting
`<em>`-tags.
> Fix escaping issue when highlighting plaintext.

- docs/HISTORY.txt
- ftw/solr/browser/available-facets.pt
This PR fixes a broken Markup in the HTML. The ID contains a whitespace which makes it hard to select it with a query-selector in js.
> Fix broken html-markup in available-facets.pt.

- docs/HISTORY.txt
- ftw/solr/browser/available-facets.pt
IDs beginning with a number are not allowed:
https://www.w3.org/TR/html4/types.html#type-id
=> It not possible to select them with css (only through workarounds)
> Fix disallowed html id name

- docs/HISTORY.txt
- ftw/solr/browser/facets.py
This PR fixes a bad return value from `collective.solr`s `facets`-function.
We always need a `list` for the `info` variable. Otherwise we cannot append more items further in the script.
> Fix bad return value for facet infos.

- ftw/solr/connection.py
- ftw/solr/tests/test_connection.py
Log UID when blob extraction fails to allow easier lookup of the content object.
Only log response errors from update and extract commands once.
> Improve error logging

- docs/HISTORY.txt
- setup.py
Declare dependency on `plone.namedfile[blobs]`, as [`ftw.solr` currently requires it](https://github.com/4teamwork/ftw.solr/blob/3b14cac8cbbee369b03977267288fba683026420/ftw/solr/handlers.py#L6) (could be made a soft dependency in the future).
> Declare dependency on plone.namedfile[blobs]

- docs/HISTORY.txt
- ftw/solr/search.py
- ftw/solr/tests/test_search.py
Properly quote roles/users with spaces.
> Fix security filter

- docs/HISTORY.txt
- ftw/solr/connection.py
- ftw/solr/tests/test_connection.py
Set the`application/x-www-form-urlencoded` Content-Type for requests to the `/update/extract` endpoint to ensure compatibility with Solr 7.3.
This is needed because something suble changed from Solr 7.2 to 7.3 where the `/update/extract` endpoint now requires you to either set the `application/x-www-form-urlencoded` content type or use a `GET` instead of a `POST` in order for it to honor the `stream.file` parameter.
With just a `POST` and no urlencoded content type, 7.3 will attempt to read the content stream from the POST body (ignoring `stream.file`), resulting in an empty stream being passed to Tika for extraction. This will then cause Tika to fail with a `ZeroByteFileException`.
I tested this invocation of the ExtractingRequestHandler for both Solr 7.2 and 7.3, so it works for both. …
> Solr 7.3 compatibility: Fix requests to ExtractingRequestHandler

- docs/HISTORY.txt
- ftw/solr/browser/search.js
This PR fixes an issue where searchterms haven't been highlighted properly:
Before:
After:
Issuer: https://extranet.4teamwork.ch/support/ivbe/tracker/125
> Fix use of highlightSearchTerms on livesearch if searching for multiple terms.

- docs/HISTORY.txt
- ftw/solr/__init__.py
- ftw/solr/configure.zcml
- ftw/solr/patches.py
- ftw/solr/testing.py
- ftw/solr/tests/test_collective_indexing_integration.py
- setup.py
This re-applies the [patch we originally had](https://github.com/4teamwork/ftw.solr/blob/1.10.0/ftw/solr/patches/reindex.py#L57-L90) in the `ftw.solr 1.x` line.
This patch optimizes `CatalogAware.reindexObjectSecurity()` so that it performs substantially better for large trees of objects. The optimization relies on the fact that when recursively reindexing security for a subtree, recursion can safely be terminated as soon as an object is encountered that didn't experience a change to the contents of its indexed security.
Without this patch, and
- `collective.solr == 2.0` the `allowedRolesAndUsers` index won't be properly updated
- `collective.solr == 2.1` the `allowedRolesAndUsers` index will be updated, but in a very inefficient way
With this patch, irrespective of the version of …
> Patch reindexObjectSecurity to optimize indexing of large trees.

- docs/HISTORY.txt
- ftw/solr/patches.py
- ftw/solr/tests/test_collective_indexing_integration.py
The reindexObjectSecurity patch relies on the fact whether the indexed value changed or not to determine when it can safely stop recursion. This check did not account for the fact that the `allowedRolesAndUsers` indexer contains a [shortcut / optimization that makes the *indexed* allowed roles not correspond exactly to the *real* allowed roles in all cases:
If any of the `Anonymous` or `Authenticated` roles are present in the allowed roles, the resulting value to be indexed [gets simplified to just that role name](https://github.com/plone/Products.CMFPlone/blob/f80809340cb8263ed5a217d8f311e26b2c98d1ef/Products/CMFPlone/CatalogTool.py#L148-L151).
This can lead to situations where the effective set of allowed roles and principals changed, but the indexed value stays the same. That's fine …
> Fix reindexObjectSecurity patch to account for special handling of system roles in allowedRolesAndUsers indexer

- docs/HISTORY.txt
- ftw/solr/handlers.py
- ftw/solr/tests/test_handlers.py
Do not add documents without any values at all.
Adding a document without values would result in clearing it.
> Fix partial reindexing (atomic updates) for fields without a value.

- docs/HISTORY.txt
- ftw/solr/browser/maintenance.py
- ftw/solr/connection.py
- ftw/solr/tests/test_connection.py
Perform soft commit on update.
This make documents available for search almost immediately after being indexed.
However changes are not yet saved to disk. Thus regular hard commits must be ensured by enabling autocommit.
The metadata of files is now indexed the same way as other content types to make them visible as soon as possible. They get indexed again using the extracting request handler which also indexes the blob data. This means that file metadata gets indexed twice because the extracting request handler does not support atomic updates.
> Near Real Time Searching

- docs/HISTORY.txt
- ftw/solr/connection.py
- ftw/solr/helpers.py
- ftw/solr/tests/data/search_with_facets.json
- ftw/solr/tests/test_response.py
For the new GEVER UI we need the possibility to optionally query for facet available values on the listing endpoint (https://github.com/4teamwork/opengever.core/issues/5738). In this PR we add parsing of the returned `facet_counts` to the `SolrResponse `.
This can be tested in conjunction with https://github.com/4teamwork/opengever.core/pull/5761
> Handle facet_counts in solr response

- docs/HISTORY.txt
- ftw/solr/handlers.py
- ftw/solr/tests/test_handlers.py
- solr-config/conf/managed-schema
This is a follow-up to #132 where support for indexing path depth was added.
We need to make sure to always update `path_depth` as well if `path` is (re)indexed:
In some cases, the `path` catalog index will be updated for an object specifically by passing `path` in the list of `idxs` of a `reindexObject()` call. One such case is [moving an object while `ftw.copymovepatches` is installed](https://github.com/4teamwork/ftw.copymovepatches/blob/1bdffdf428e452af851aa29da910d6e2824343af/ftw/copymovepatches/cmfcatalogaware.py#L82-L88).
Because `path_depth` is not a Plone catalog index, it will not be listed in these cases (by Plone or a Plone addon product). It still needs to be updated though in those cases, because it's contents are functionally dependent on the object's path.
We therefore …
> Make sure to always update 'path_depth' if 'path' is (re)indexed.

- docs/HISTORY.txt
- ftw/solr/handlers.py
A `return` statement was missing.
> Fix error when trying to delete an object without a unique key

- docs/HISTORY.txt
- ftw/solr/connection.py
- ftw/solr/handlers.py
- ftw/solr/testing.py
- ftw/solr/tests/test_connection.py
- ftw/solr/tests/test_handlers.py
- setup.py
The metadata of files is now indexed the same way as other items.
The SearchableText is first extracted using Solr Cell and then indexed as an
atomic update.
Fixes #137
> Use Solr Cell only for text extraction

- docs/HISTORY.txt
- ftw/solr/handlers.py
- ftw/solr/tests/test_handlers.py
The special handling for the `path_depth` field introduced in #134 only works when the `path_depth` is configured as field in the schema.
> Fix 'path_depth' indexing handling, when its not part of the schema.

- docs/HISTORY.txt
- ftw/solr/handlers.py
- ftw/solr/tests/test_handlers.py
The `DefaultIndexHandler` handled this correctly, but the `ATBlobFileIndexHandler` and `DexterityItemIndexHandler` didn't.
In cases where `attributes` only consists of index names that don't correspond to a field in the Solr schema, we did end up in a situation where `data` was `None`, and was sent to Solr as
the "document" in an atomic update command:
```
"add": {"doc": null}
```
This would Solr to respond with a `400`, and reject the entire request which could contain other, valid updates.
---
Solr Response in the case of this error:
```json
{  
"responseHeader":{  
"status":400,
"QTime":57
},
"error":{  
"msg":"Expected: OBJECT_START but got NULL at [1968]",
"code":400,
"metadata":[  
"error-class",
"org.apache.solr.common.SolrException",
"root-error-class", …
```
> Avoid sending atomic update commands with null-documents

- docs/HISTORY.txt
- ftw/solr/skins/ftw_solr/jquery.highlightsearchterms.js
This is so that everything can be searched for and be easily found regardless
of what it is. This eg. also filtered out words including and like eg. "hand".
> Remove filter of or/and/not in searchterm highlighting 1.x

- README.rst
- docs/HISTORY.txt
Fix syntax and highlight blocks correctly. ATM PyPI looks like this 
In ftw.solr 2.x this is already fixed but because 1.x is still used in many places it should be backported to 1.x as well. 
current 1.x
---
current 2.x
---
> Fix rst syntax of reamde 1.x

- docs/HISTORY.txt
- ftw/solr/browser/resources/livesearch.scss
Close https://github.com/4teamwork/demo.intranet/issues/3
When a contents description was too long the search results overlay grew out of the page.
With this change we limit it to 80% of the viewport for desktop computers while it stays 100% for mobile devices as before.
The search overlay is not growing out of the page anymore if there is a long description.
For mobile devices nothing changed.
> Limit max width for search overlay.

- README.rst
- docs/HISTORY.txt
- ftw/solr/connection.py
- ftw/solr/handlers.py
- ftw/solr/helpers.py
- ftw/solr/tests/test_connection.py
- ftw/solr/tests/test_handlers.py
- ftw/solr/tests/test_helpers.py
- ftw/solr/zcml.py
- setup.py
Add support for uploading blobs to Solr Cells `extract` handler via HTTP POST (instead of passing it a file path that causes the extract handler retrieve the blob from the blob storage on the filesystem).
This introduces a new connection configuration option `upload_blobs` (default: `False`). If set, `ftw.solr` will upload the blob's content with the HTTP POST request made to the `extract` handler. This allows setups where Solr doesn't run on the same machine where the blob storage is located.
File upload is performed in a streaming fashion with HTTP/1.1 chunked transfer to avoid loading the entire blob into memory.
This is part of 4teamwork/opengever.core#6023.
> Add support for uploading blobs to extract handler.

- docs/HISTORY.txt
- ftw/solr/browser/configure.zcml
The livesearch accesses "search-facets" on the current context and when
the user was on a contentish object (like the detail view of an
ftw.addressblock.Addressblock or the fron-page created on the default
plone installation) the livesearch view threw an error because
"search-facets" was not available for that object.
> Fix livesearch for while user is on contentish object

- docs/HISTORY.txt
- ftw/solr/converters.py
- ftw/solr/tests/test_converters.py
Implement formatting to support years before 1900 for `date` and `datetime` instances.
Python 2.7 can't handle that yet as per https://docs.python.org/2/library/datetime.html#strftime-strptime-behavior.
I tried various approaches but ended up implementing the formatting myself as has already been done for `DateTime` instances. To prevent any issues with solr i'd like to keep the output stable and avoid changing the string representation of dates too much, especially since this is intended as a bugfix level release. Switching to `isoformat` or the `arrow` library would all have significantly changed the iso8601 string.
> Fix to_iso8601 for years before 1900.

- docs/HISTORY.txt
- ftw/solr/handlers.py
- ftw/solr/tests/test_handlers.py
Newer Plone versions provide an empty list of indexes while previous version provided `None`.
This commit contains the same changes as the commit https://github.com/4teamwork/ftw.solr/pull/147/commits/e7f58e50d4771594d5cc3a32062279a94c95ea83, but for the DX handler this time.
> Fix check for no attributes

- docs/HISTORY.txt
- ftw/solr/converters.py
- ftw/solr/tests/test_converters.py
When milliseconds of a `DateTime` are above 999500 python string formatting rounds up the value. This leads to an ISO 8601 date format strings with a value of 60 for the [ss] (second ) part. Solr considers such date format strings invalid and throws an error, e.g.:
```
Invalid Date in Date Math String:'2015-04-07T14:43:60.000Z'
```
This will result in the corresponding object not being indexed or updated in solr by `ftw.solr`.
With this PR we fix the issue by splitting the `seconds` part of a `DateTime` into separate seconds and milliseconds parts and also pass them as separate arguments to string formatting.
additionally i've reproduced the timestamp issue locally. i have verified that with this fix the solr error no longer pops up and `bin/instance solr sync` is successful and manages …
> Fix rounding errors with DateTime milliseconds.

- docs/HISTORY.txt
- ftw/solr/tests/test_converters.py
- ftw/solr/upgrades/20200401111512_update_modified_index/upgrade.py
In https://github.com/4teamwork/ftw.solr/issues/165 we fixed a rounding issue with the conversion of zope `DateTime` objects. We now need to update the `modified` index in solr to mirror that change and avoid having half the objects recognised as out of sync...
For the implementation of the upgrade, I copied the code from `ftw.solr.browser.maintenance` and tried to modify it as little as possible. The main differences are:
- Use brains instead of objects as source of data
- Only sync the `modified` index for objects that were marked as in sync before the change in rounding introdiced in https://github.com/4teamwork/ftw.solr/issues/165 but are now recognised as out of sync. These are the objects are marked as out of sync just because of the change in rounding of `modified`
I also add tests …
> Update the modified index to match new rounding of zope DateTime

- docs/HISTORY.txt
- ftw/solr/upgrades/20200401111512_update_modified_index/upgrade.py
We cannot doom the transaction in that upgrade, as this would doom changes from other upgrade steps executed in the same transaction...
Also mark the upgrade as deferrable.
> Fix upgrade step to update the modified index where necessary

- docs/HISTORY.txt
- ftw/solr/commands.py
In the maintenance scripts we rely on the owner of the plone site to be a system. It seems that we have many deployments for which the plone site owner is `admin`, a user that does not exist, and the maintenance scripts therefore get executed as anonymous with obvious consequences, i.e. they fail as not all objects can be accessed.
The proposed fix comes from how this is done for `bin/instance run` scripts (https://github.com/plone/plone.recipe.zope2instance/blob/master/src/plone/recipe/zope2instance/ctl.py#L691-L694).
As to why certain of our sites are owned by the `admin` user, here is what I found out:
- Before creating the plone site, the standard plone `admin; admin` user is available as system user, and you can login with that user to setup the plone site. I think the `acl-users` …
> Make sure maintenance scripts are run as system user.

- docs/HISTORY.txt
- ftw/solr/browser/maintenance.py
- ftw/solr/commands.py
- ftw/solr/tests/test_maintenance.py
Wit this PR we add an optional max_diff argument to the solr maintenance view and to `bin/instance solr` command line script for the `diff` and `sync` commands. We change the default behavior of verbosely logging all UIDs that are not in sync to only logging the first five by default. Instead we now also log the total number of items not in sync in each category.
The amount of items to log can be adjusted via command line and it is still possible to log all UIDs should one wish to do so. The change is motivated by the fact that in practice we are usually more interested in just the number of items not in sync and the very verbose logging impedes our ability to easily read the script output.
By default only five UIDs are logged in `diff`:
```
$ bin/instance solr diff
2020-05-27 11:41:00 …
```
> Truncate solr maintenance logging. Add max_diff option to limit nof diffed objects.

- docs/HISTORY.txt
- ftw/solr/browser/maintenance.py
This change adds a `TimedRotatingFileHandler` to the already existing `ftw.solr.maintenance` logger, so that **maintenance commands get logged to a dedicated logfile**.
As discussed with @buchi and @deiferni, the log directory is determined by deriving it from the location of Zope's EventLog.
I decided to use a single logfile, `solr-maintenance.log`, for all processes (instances), even though this in theory could lead to concurrency issues because multiple processes might be writing to the same file.
However, I deemed this risk acceptable because
- Maintenance commands will never (intentionally) be executed in parallel. So unlike the event log, this is not a file that's actively being written to most of the time.
- There should not be a risk of actually losing log data (lines). The worst …
> Log maintenance commands to a dedicated logfile.

- docs/HISTORY.txt
- ftw/solr/browser/maintenance.py
- setup.py
Solr documents where the `created` field value is missing will now be treated as out of sync with portal catalog. This fixes an issue we had in production where documents that were only inserted partially in solr would not be picked up by `diff` as their `modified` field was provided correctly.
We assume the partial documents were created as following:
- the user created content in plone and queued an add which would fail in rare cases before the fix in https://github.com/4teamwork/ftw.solr/pull/158
- thus a document would not have been added to solr
- during an upgrade or other reindex operation we have queued an atomic update for the plone content which only updated a subset of the fields, e.g. by sending the following update command to solr
```
"add": {"doc": {"path": {"set": …
```
> Treat docs with no `created` field as out of sync in solr `diff` and `sync`. 

- docs/HISTORY.txt
- ftw/solr/connection.py
- ftw/solr/tests/test_connection.py
- ftw/solr/tests/utils.py
This fixes an issue where SearchableText for a given document gets extracted several times from different blobs in one transaction. This is inefficient and causes problems because older extract_commands try to extract from blobs that have been overwritten in the meantime, having uncommitted changes which will lead to errors and the document not getting indexed at all. Instead we now filter the list of extract_commands to only keep the relevant ones.
For https://4teamwork.atlassian.net/browse/CA-1104
> Cleanup extract_commands before sending them to solr.

- docs/HISTORY.txt
- ftw/solr/handlers.py
We were skipping attributes with a value of `None` when indexing data in solr. This prevents setting an attribute back to `None`. I don't think this was necessary for anything, at least I did not find any information as to why we were skipping these attributes.
Proof that the fix works in Gever: https://github.com/4teamwork/opengever.core/pull/6809
For https://4teamwork.atlassian.net/browse/CA-1336
> Fix setting document_type back to None

- docs/HISTORY.txt
- ftw/solr/handlers.py
- ftw/solr/tests/test_handlers.py
Two problems surfaced that hinder reindexing only `SearchableText` and `UID` in opengever.core. `UID` is of course used only to avoid reindexing everything in Gever catalog, so we really only want to reindex the `SearchableText` in solr. When indexes are specified, `collective.indexing` will actually pass the `attributes` as a tuple. The handler in `ftw.solr`, tries to remove `SearchableText` from that tuple, which fails.
Moreover the `add_atomic_update_modifier` will return `None` whenever the `attributes` list contains only the `unique_key`, i.e. `UID` in our case. In such cases, the call of the `extract` method would fail, because
it tries to retrieve the `unique_key` from that empty dictionary.
For https://4teamwork.atlassian.net/browse/CA-1361
> Fix indexing of SearchableText only for objects with primary field.

- docs/HISTORY.txt
- ftw/solr/browser/search.py
- ftw/solr/browser/selected-facets.pt
This PR solves two common issues according to our sentry entries:
- path param with a random value -> catch KeyError while traversing a random path.
- random value for facets -> Needs to contain a `:`, the rendering facets failed if it did not.
> Make solr search result page more robust agains random querystrings

- docs/HISTORY.txt
- ftw/solr/search.py
- ftw/solr/tests/test_search.py
Solr queries are now also used in some upgrade steps / maintenance jobs. As such it seems important to ensure that no objects are omitted because of restricted access. Of course normally this should not make any difference, as the user executing the upgrades / maintenance is manager, but typically an object with broken `allowedRolesAndUsers` index would be invisible in normal search...
For https://4teamwork.atlassian.net/browse/CA-1335
> Add an unrestricted search method to SolrSearch.

- docs/HISTORY.txt
- ftw/solr/browser/maintenance.py
This is used when wiping and setting up Gever again. See https://github.com/4teamwork/opengever.core/pull/7180
> Add flag to force clear solr even if not enabled.

- docs/HISTORY.txt
- ftw/solr/browser/maintenance.py
- ftw/solr/commands.py
The `allowedRolesAndUsers` index is crucial for the security and it is therefore useful to be able to make sure that this index is up to date. Testing the maintenance view is not really possible with our current testing infrastructure. 
For [CA-4291](https://4teamwork.atlassian.net/browse/CA-4291)
> Add option to check allowedRolesAndUsers in solr diff and sync.

- docs/HISTORY.txt
- ftw/solr/browser/maintenance.py
- ftw/solr/connection.py
- ftw/solr/interfaces.py
- ftw/solr/tests/test_connection.py
- ftw/solr/upgrades/20200401111512_update_modified_index/upgrade.py
- ftw/solr/upgrades/20220718103046_add_enable_updates_in_post_commit_hook_setting/registry.xml
- ftw/solr/upgrades/20220718103046_add_enable_updates_in_post_commit_hook_setting/upgrade.py
The main advantage to execute the update commands in a post commit hook is to shorten the time the ZODB is locked. On disadvantage is that [the transaction does not get roll-backed when the after commit hooks fail](https://github.com/zopefoundation/transaction/blob/1.1.1/transaction/_transaction.py#L412-L421). This is of no concern here, as we anyway do not make the transaction fail when the [updates in solr go wrong](https://github.com/4teamwork/ftw.solr/blob/master/ftw/solr/connection.py#L166-L171). So there is no real drawback of executing all the update commands in an after transaction hook.
For https://4teamwork.atlassian.net/browse/CA-4291
> Add option to execute update commands in post commit hook.

- docs/HISTORY.txt
- ftw/solr/connection.py
In situations where a Plone site doesn't exist yet (e.g. when attempting to purge Solr during Plone site setup), there won't be a Plone registry, and `queryUtility(IRegistry)` will return `None`, and the `updates_in_post_commit_enabled()` helper will fail.
This change fixes this by returning `True` (the settings interface's default) in this case.
(Fixes an issue where a GEVER can't be set up locally with the `[ ] Purge Solr` flag any more)
> Make updates_in_post_commit_enabled() helper more robust:

- docs/HISTORY.txt
- ftw/solr/browser/maintenance.py
Fix solr sync maintenance command not committing all batches.
Because the maintenance view doesn't commit the ZODB transaction, Solr commits must not be deferred into a ZODB transaction post commit hook in this view, otherwise they won't get executed.
This lead to the last (or only) batch of items not getting committed (discovered during GDGS recovery).
This was partially addressed in #191, but some conn.commit()'s were missed (or maybe introduced later)
> Fix solr sync maintenance command not committing all batches.

- docs/HISTORY.txt
- ftw/solr/search.py
Not specifying fl will return all fields, includung searchableText which will typically dramatically impact performance.
Tests should get fixed with https://github.com/4teamwork/ftw-buildouts/pull/215
For https://4teamwork.atlassian.net/browse/CA-5921
> Log warning when a search is performed without specifying fl.

- docs/HISTORY.txt
- ftw/solr/commands.py
- test-plone-5.2.x-py37.cfg
- test-plone-5.2.x-py38.cfg
Stripping arguments is only needed if ftw.solr is installed with buildout using the `plone.recipe.zope2instance` recipe.
It breaks installations that rely on `Zope2.Startup.zopectl`.
> Fix argument parsing of zopectl command
